
clear
clc
wd = 'C:\Users\Martin\Desktop\EMGVB_REV';
cd(wd)
addpath(genpath('VBLab'))
addpath('Utils')
addpath(genpath('HAR'))

%%

load('Make_data\HARdata2.mat')
Data = mk_train_test_data(HAR.SPX{:,:},0.8);

lm.fit  = fitlm(Data.train(:,2:end),Data.train(:,1),'linear','Intercept',false);
lm.beta = lm.fit.Coefficients.Estimate;
lm.tpar  = [lm.beta;log(lm.fit.RMSE)];
lm.par   = [lm.beta;lm.fit.RMSE];
[~,~,~,~,lm.train_ll,lm.train_mse,lm.train_qlik]  = get_XYmu(Data.train,lm.tpar);
[~,~,~,~,lm.test_ll,lm.test_mse,lm.test_qlik]    = get_XYmu(Data.test,lm.tpar);

lm.perf = [nan,lm.train_ll,lm.train_mse, lm.train_qlik,nan,lm.test_ll,lm.test_mse,lm.test_qlik];

seed = 2022;

setting.Prior.Mu        = 0;
setting.Prior.Sig       = 5;


%%

opt.lr              = 0.001;
opt.maxiter         = 800;
opt.maxPatience     = 300;
opt.stepAdaptive    = 600;
opt.maxGrad         = 50000;
opt.nSample         = 50;
opt.clipInit        = 1000;
opt.SigInitScale    = 0.01;
opt.MeanInit        = lm.tpar.*0.95;

% setting.SigFactor = 2;

% ---------------------------------
setting.isDiag = 0;
setting.useHfunc = 0;


rng(seed)
pMGVB = MGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);

pMGVB.Post.mu

rng(seed)
pEMGVB = EMGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',2*opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);

rng(seed)
pQBVI = QBVI_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);


% ---------------------------------
setting.isDiag      = 0;
setting.useHfunc    = 1;

rng(seed)
pMGVB_h = MGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);

rng(seed)
pEMGVB_h = EMGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',2*opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);


rng(seed)
pQBVI_h = QBVI_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);

% ---------------------------------
setting.isDiag = 1;
setting.useHfunc = 0;

rng(seed)
pMGVB_d = MGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);

rng(seed)
pEMGVB_d = EMGVB_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',2*opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);


rng(seed)
pQBVI_d = QBVI_har(@h_func_m,Data,...
    'NumParams',5,...
    'MeanInit',opt.MeanInit,...
    'Setting',setting,...
    'LearningRate',opt.lr,...
    'NumSample',opt.nSample,...
    'MaxPatience',opt.maxPatience,...
    'MaxIter',opt.maxiter,...
    'GradWeight',0.4,...
    'WindowSize',30,...
    'SigInitScale',opt.SigInitScale,...
    'StepAdaptive',opt.stepAdaptive,...
    'GradientMax',opt.maxGrad,...
    'GradClipInit',opt.clipInit,...
    'SaveParams',true,...
    'Verbose',2,...
    'LBPlot',false);


plot(pEMGVB.Post.LB_smooth)
hold on
plot(pMGVB.Post.LB_smooth,'--')
plot(pQBVI.Post.LB_smooth,':r')
hold off


%%


rng(seed)
Mdl = LinearRegression(5,...
    'Prior',{'Normal',[setting.Prior.Mu setting.Prior.Sig]},...
    'Intercept',false...
    );

mcmc.n = 50000;
pMCMC = MCMC(Mdl,Data.train,...    
    'NumMCMC',mcmc.n,...        
    'SigScale',1,...
    'ParamsInit',lm.tpar,...
    'Verbose',5000); 


[mcmc.mean,mcmc.std,mcmc.params] = getParamsMean(pMCMC);
mcmc.tpar   = mcmc.mean';
mcmc.std    = mcmc.std';
mcmc.chain  = pMCMC.Post.theta(pMCMC.BurnIn+1:end,:);
mcmc.par    = [mcmc.tpar(1:end-1);exp(mcmc.tpar(end))];

[~,~,~,~,mcmc.train_ll,mcmc.train_mse,mcmc.train_qlik] = get_XYmu(Data.train,mcmc.tpar);
[~,~,~,~,mcmc.test_ll,mcmc.test_mse,mcmc.test_qlik] = get_XYmu(Data.test,mcmc.tpar);
mcmc.perf = [nan, mcmc.train_ll,mcmc.train_mse,mcmc.train_qlik,...
             nan, mcmc.test_ll, mcmc.test_mse, mcmc.test_qlik];


save('HAR\Save\Har.mat','pEMGVB','pMGVB','pQBVI','pEMGVB_d','pMGVB_d','pQBVI_d','pEMGVB_h','pMGVB_h','pQBVI_h',...
    'Data','lm','setting','Mdl','pMCMC','mcmc','opt')

%% Table

h = @(x) x.Post.perf([1,2,3,4,6,7,8]);
f = @(x) x.Post.par;

tab_perf    = [ h(pEMGVB);h(pMGVB);h(pQBVI);...
                h(pEMGVB_h);h(pMGVB_h);h(pQBVI_h);...
                h(pEMGVB_d);h(pMGVB_d);h(pQBVI_d);...
                mcmc.perf([1,2,3,4,6,7,8]);lm.perf([1,2,3,4,6,7,8])];

tab_est     = [ f(pEMGVB);f(pMGVB);f(pQBVI);...
                f(pEMGVB_h);f(pMGVB_h);f(pQBVI_h)
                f(pEMGVB_d);f(pMGVB_d);f(pQBVI_d);...
                mcmc.par';lm.par'];


%%

writematrix(tab_perf,'HAR\Save\Har_tables.xls','Sheet','perf')
writematrix(tab_est,'HAR\Save\Har_tables.xls','Sheet','est')

%%
load("Colors.mat")
close
xp = 31:800;
lw = 1.4;

subplot(1,3,1)
plot(xp,pEMGVB.Post.LB_smooth,'LineWidth',lw,'Color',col{1})
hold on
plot(xp,pMGVB.Post.LB_smooth,'-','LineWidth',lw,'Color',col{3})
grid
xlabel('Iteration','Interpreter','Latex')
title('Lower bound','Interpreter','Latex')
xlim([0 opt.maxiter])
plot(xp,pEMGVB_d.Post.LB_smooth,':','LineWidth',lw,'Color',col{1})
plot(xp,pMGVB_d.Post.LB_smooth,':','LineWidth',lw,'Color',col{3})

xline(pEMGVB.Post.LB_indx,'Color',col{1})
xline(pMGVB.Post.LB_indx,'Color',col{3})
xline(pEMGVB_d.Post.LB_indx,':','Color',col{1})
xline(pMGVB_d.Post.LB_indx,':','Color',col{3})
hold off

hold on
t1 = plot([nan,nan],'-','Color',col{1},'LineWidth',lw);
t2 = plot([nan,nan],'-','Color',col{3},'LineWidth',lw);
t3 = plot([nan,nan],':','Color',col{1},'LineWidth',lw);
t4 = plot([nan,nan],':','Color',col{3},'LineWidth',lw);
t5 = plot([nan,nan],'-','Color',col{9});
hold off

grid
xlabel('Iteration','Interpreter','Latex')
ylabel('Lower bound','Interpreter','Latex')
xlim([0 opt.maxiter])
legend([t1,t2,t3,t4,t5],{'EMGVB','MGVB','EMGVB diag.','MGVB diag.','$t^\star$'},...
    'Location','southeast','Interpreter','latex')



subplot(1,3,2)
yyaxis left
plot(pEMGVB.Post.train.mse,'LineWidth',lw,'Color',col{2})
hold on
plot(pMGVB.Post.train.mse,'--','LineWidth',lw,'Color',col{2})
hold off
ytickformat('%.1f')
ax = gca;
ax.YColor  = col{2};

yyaxis right
plot(pEMGVB.Post.test.mse,'LineWidth',lw,'Color',col{4})
hold on
plot(pMGVB.Post.test.mse,'--','LineWidth',lw,'Color',col{4})
hold off
ytickformat('%.1f')

hold on
t1 = plot([nan,nan],'-','Color',col{2},'LineWidth',lw);
t2 = plot([nan,nan],'--','Color',col{2},'LineWidth',lw);
t3 = plot([nan,nan],'-','Color',col{4},'LineWidth',lw);
t4 = plot([nan,nan],'--','Color',col{4},'LineWidth',lw);
hold off
ytickformat('%.1f')
xlim([0 opt.maxiter])
ax = gca;
ax.YColor  = col{4};
legend([t1,t2,t3,t4], {'EMGVB train','MGVB train','EMGVB test','MGVB test'})
title('MSE','Interpreter','latex')



subplot(1,3,3)
yyaxis left
plot(pEMGVB.Post.train.qlik*100,'LineWidth',lw,'Color',col{2})
hold on
plot(pMGVB.Post.train.qlik*100,'--','LineWidth',lw,'Color',col{2})
hold off
ytickformat('%.2f')
ax = gca;
ax.YColor  = col{2};

yyaxis right
plot(pEMGVB.Post.test.qlik*100,'LineWidth',lw,'Color',col{4})
hold on
plot(pMGVB.Post.test.qlik*100,'--','LineWidth',lw,'Color',col{4})
hold off

hold on
t1 = plot([nan,nan],'-','Color',col{2},'LineWidth',lw);
t2 = plot([nan,nan],'--','Color',col{2},'LineWidth',lw);
t3 = plot([nan,nan],'-','Color',col{4},'LineWidth',lw);
t4 = plot([nan,nan],'--','Color',col{4},'LineWidth',lw);
hold off
ytickformat('%.2f')
xlim([0 opt.maxiter])
ax = gca;
ax.YColor  = col{4};
legend([t1,t2,t3,t4], {'EMGVB train','MGVB train','EMGVB test','MGVB test'})
title('Qlik ($\times 10^2)$','Interpreter','latex')

set_fig(1700,400,700,150)
savePDF('HAR\Plots\','Har_perf')

%%


